openapi: 3.1.0
info:
  title: Stability AI Image API
  version: 1.0.0
  description: API for generating and upscaling images using Stability AI.
servers:
  - url: https://9d49-182-180-57-9.ngrok-free.app
    description: Local development server
paths:
  /generate_image:
    post:
      summary: Generate an image based on a text prompt
      description: Generates an image using Stability AI's core image generation API.
      operationId: generateImage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                prompt:
                  type: string
                  description: The text prompt to generate the image.
              required:
                - prompt
      responses:
        '200':
          description: The URL of the generated image.
          content:
            application/json:
              schema:
                type: object
                properties:
                  image_url:
                    type: string
                    format: uri
                    description: The URL pointing to the generated image.
        '400':
          description: Invalid input or missing prompt.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /upscale_image:
    post:
      summary: Upscale an image from a URL
      description: Downloads an image from the provided URL, sends it to Stability AI's fast upscaler, and returns the URL of the upscaled image.
      operationId: upscaleImage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                image_url:
                  type: string
                  format: uri
                  description: The URL of the image to upscale. The URL must be accessible by the server.
              required:
                - image_url
      responses:
        '200':
          description: The URL of the upscaled image.
          content:
            application/json:
              schema:
                type: object
                properties:
                  image_url:
                    type: string
                    format: uri
                    description: The URL pointing to the upscaled image.
        '400':
          description: Invalid input or failed to download the image from the URL.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
